bonsai_gestor_homepage:
    pattern:  /gestor
    defaults: { _controller: BonsaiGestorBundle:Gestor:index }

bonsai_gestor_homepage_dos:
    pattern:  /gestor/
    defaults: { _controller: BonsaiGestorBundle:Gestor:index }

bonsai_gestor_agregar:
    pattern: /gestor/agregar
    defaults: { _controller: BonsaiGestorBundle:Agregar:agregar }

bonsai_gestor_ficha:
    pattern: /gestor/ficha/{id}/{nombre}
    defaults: { _controller: BonsaiGestorBundle:Ficha:mostrar }
    requirements:
        id:  \d+