bonsai_gestor_homepage:
    pattern:  /gestor
    defaults: { _controller: BonsaiGestorBundle:Gestor:index }

bonsai_gestor_homepage_dos:
    pattern:  /gestor/
    defaults: { _controller: BonsaiGestorBundle:Gestor:index }

bonsai_gestor_agregar:
    pattern: /gestor/agregar
    defaults: { _controller: BonsaiGestorBundle:Agregar:agregar }

bonsai_gestor_ficha:
    pattern: /gestor/ficha/{id}
    defaults: { _controller: BonsaiGestorBundle:Ficha:mostrar }
    requirements:
        id:  \d+

bonsai_gestor_borrar:
    pattern: /gestor/borrar/{id}
    defaults: { _controller: BonsaiGestorBundle:Gestor:borrar }
    requirements:
        id:  \d+

bonsai_gestor_editar:
    pattern: /gestor/editar/{id}
    defaults: { _controller: BonsaiGestorBundle:Agregar:editar }
    requirements:
        id:  \d+